# tonemirror-server docker-compose.yml

services:
  nginx:
    image: nginx
    container_name: nginx-server
    ports:
      - "28282:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # 커스텀 로그 추적을 위해 디폴트 로그를 무력화
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - spring
      - fastapi
      - frontend
    restart: unless-stopped

  spring:
    build:
      context: ./tonemirror-spring
      dockerfile: ../spring.Dockerfile
    container_name: spring-server
    volumes:
      - ./storage:/app/storage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - IMAGE_PATH=${IMAGE_PATH}
      - FASTAPI_URL=${FASTAPI_URL}
    depends_on:
      - mysql
  
  fastapi:
    build:
      context: ./tonemirror-python
      dockerfile: ../python.Dockerfile
    container_name: fastapi-server
    environment:
      - IMAGE_PATH=/app/storage
      - BASE_URL=http://localhost:28282/ai
      # db.py 의 os.environ Key와 일치시키기 위한 매핑
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./storage:/app/storage
    depends_on:
      - mysql
  
  frontend:
    build:
      context: ./tonemirror-web
      dockerfile: ../web.Dockerfile
    container_name: react-server
  
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "28336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: tonemirror
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped