# tonemirror-server/nginx/nginx.conf

events{
    worker_connections 1024;
}
http{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format debug_routing '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             'to_upstream: $upstream_addr '
                             'orig_path: $request_uri';

    access_log /var/log/nginx/access.log debug_routing;

    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        location / {
            set $frontend_url http://frontend:5173;
            proxy_pass $frontend_url$request_uri;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location /api/ {
            set $spring_url http://spring:8080;
            proxy_pass $spring_url$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /ai/ {
            set $fastapi_url http://fastapi:8000;
            proxy_pass $fastapi_url/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}